---
name: Template-Plugin-DtFormatter
version: 1.00
author:
  - 'Michele Beltrame, C<mb@italpro.net>.'
abstract: |-
  Easily create formatted string from DateTime
  objects
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  DateTime: 0.36
  DateTime::Format::Strptime: 1.07
  Template: 2.15
provides:
  Template::Plugin::DtFormatter:
    file: lib/Template/Plugin/DtFormatter.pm
    version: 1.00
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
